# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/iley/clionprojects/op

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/iley/clionprojects/op

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/iley/clionprojects/op/CMakeFiles /Users/iley/clionprojects/op//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/iley/clionprojects/op/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named op

# Build rule for target.
op: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 op
.PHONY : op

# fast build rule for target.
op/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/build
.PHONY : op/fast

Alg.o: Alg.c.o
.PHONY : Alg.o

# target to build an object file
Alg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/Alg.c.o
.PHONY : Alg.c.o

Alg.i: Alg.c.i
.PHONY : Alg.i

# target to preprocess a source file
Alg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/Alg.c.i
.PHONY : Alg.c.i

Alg.s: Alg.c.s
.PHONY : Alg.s

# target to generate assembly for a file
Alg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/Alg.c.s
.PHONY : Alg.c.s

File_out.o: File_out.c.o
.PHONY : File_out.o

# target to build an object file
File_out.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/File_out.c.o
.PHONY : File_out.c.o

File_out.i: File_out.c.i
.PHONY : File_out.i

# target to preprocess a source file
File_out.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/File_out.c.i
.PHONY : File_out.c.i

File_out.s: File_out.c.s
.PHONY : File_out.s

# target to generate assembly for a file
File_out.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/File_out.c.s
.PHONY : File_out.c.s

Gen_file.o: Gen_file.c.o
.PHONY : Gen_file.o

# target to build an object file
Gen_file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/Gen_file.c.o
.PHONY : Gen_file.c.o

Gen_file.i: Gen_file.c.i
.PHONY : Gen_file.i

# target to preprocess a source file
Gen_file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/Gen_file.c.i
.PHONY : Gen_file.c.i

Gen_file.s: Gen_file.c.s
.PHONY : Gen_file.s

# target to generate assembly for a file
Gen_file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/Gen_file.c.s
.PHONY : Gen_file.c.s

Var_str.o: Var_str.c.o
.PHONY : Var_str.o

# target to build an object file
Var_str.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/Var_str.c.o
.PHONY : Var_str.c.o

Var_str.i: Var_str.c.i
.PHONY : Var_str.i

# target to preprocess a source file
Var_str.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/Var_str.c.i
.PHONY : Var_str.c.i

Var_str.s: Var_str.c.s
.PHONY : Var_str.s

# target to generate assembly for a file
Var_str.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/op.dir/build.make CMakeFiles/op.dir/Var_str.c.s
.PHONY : Var_str.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... op"
	@echo "... Alg.o"
	@echo "... Alg.i"
	@echo "... Alg.s"
	@echo "... File_out.o"
	@echo "... File_out.i"
	@echo "... File_out.s"
	@echo "... Gen_file.o"
	@echo "... Gen_file.i"
	@echo "... Gen_file.s"
	@echo "... Var_str.o"
	@echo "... Var_str.i"
	@echo "... Var_str.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

